// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofeinemvlkjtiesyddxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mZWluZW12bGtqdGllc3lkZHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTY2NjIsImV4cCI6MjA2MTIzMjY2Mn0._B4VwxmS4m27mOew2HXDDA8-2uSCYA4yHUP0g1TdE5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);